< POST /cluster/ HTTP/1.1
< Host: 127.0.0.1:8798
< User-Agent: python-requests/2.25.1
< Accept-Encoding: gzip, deflate
< Accept: */*
< Connection: keep-alive
< Content-Length: 202
< Content-Type: application/json
< 
< {"cluster_type_id": 100, "name": "ZZqHyiEiBcDEWoNWPWifnpZeNgExsxnSHt", "description": "GqIlvZzeCDHfIlqteQNzdbEbkcGiQZNsjfPMWNhjYdbAijSZYZUHoPkKmBjFJeMoAxihDuBGnNgYKbCaCmaLwdsAhfPRiXOvJxxJUmSfggruhAkyN"}
> HTTP/1.1 422 Unprocessable Entity
> Date: Wed, 14 Apr 2021 11:39:12 GMT
> Server: Apache/2.4.38 (Debian)
> X-Powered-By: PHP/8.0.3
> Cache-Control: no-cache, private
> Content-Length: 64
> Keep-Alive: timeout=5, max=100
> Connection: Keep-Alive
> Content-Type: application/json
> 
{"cluster_type_id":["The selected cluster type id is invalid."]}